### ISSUE TITLE
focus   input   type="number"

### ISSUE THREAD

**Issue by Jquery-love** [ftlabs/fastclick#518] opened 2017-02-15 05:39 UTC
Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

line:331 targetElement.setSelectionRange(length, length);   replace with
targetElement.select(length, length)

**Comment by quarterto** [comment] 2017-05-17 09:58
Thanks for the report, this is a duplicate of #358

**Closed by quarterto** 2017-05-17 09:58 UTC
