### ISSUE TITLE
"RangeError: Maximum call stack size exceeded."  running on i

### ISSUE THREAD

**Issue by johnnyshields** [ftlabs/fastclick#352] opened 2015-01-08 15:06 UTC
Using fastclick version 1.0.3

Stacktrace:
```
[native code]:13743:23    dispatchEvent
bower_components/fastclick/lib/fastclick.js:296   sendClick
http://xxx.com/assets/vendor.js:91973:17    onTouchEnd
http://xxx.com/assets/vendor.js:91477:42
```

This line which triggered the error was in FastClick.prototype.sendClick function.
```
targetElement.dispatchEvent(clickEvent);
```

**Comment by rowanbeentje** [comment] 2015-01-08 15:13
Duplicate of #353

**Closed by rowanbeentje** 2015-01-08 15:13 UTC
